### ISSUE TITLE
Investigate how to secure connections between databases

### ISSUE THREAD

**Issue by tlmn** [DW-ReCo/dw-kid2-graph-frontend-prototype#12]
Saw this [issue](https://github.com/pouchdb/pouchdb-server/issues/169) and was wondering whether that has any implications for us. Or would we simply wrap a server around the remote PouchDB instance? @nikonikoniko

**Comment by nikonikoniko** [comment]
The most likely case is that we would put any couchDb or pouchDB instance behind an nginx or apache proxy (which would supply the https), Or another kind of server if we have any form of authentication.

**Comment by tlmn** [comment]
Yeah thought so, still wanted to note that it doesnt come with SSL out of the box
