### ISSUE TITLE
Change the nextjs directory

### ISSUE THREAD

**Issue by nikonikoniko** [DW-ReCo/dw-kid2-graph-frontend-prototype#6]
Ideally, our folder structure should looks somthing like this: 

```
...
package.json
src/
  next/
    pages/
  db/
  config/
  utils/
```

next is owning the `src` directory at the moment, it would be nice to change this

**Comment by tlmn** [comment]
fixed in af6d5381a24f9fba1a24e75bff846b09bf8267fc
